import { useState, useEffect, useContext } from 'react'
import { useParams, useNavigate, useLocation } from 'react-router-dom'
import axios from 'axios'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { AuthContext } from '../context/AuthContext'

function priorityBadge(p) {
  if (!p) return 'badge-gray'
  if (p.toLowerCase() === 'high')   return 'badge-red'
  if (p.toLowerCase() === 'medium') return 'badge-orange'
  return 'badge-gray'
}

function formatDate(iso) {
  try { return new Date(iso).toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' }) }
  catch { return iso || '' }
}

export default function ViewPlan() {
  const { id } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  
  const [plan, setPlan]   = useState(location.state?.plan || null)
  const [loading, setLoading] = useState(!location.state?.plan)
  const [error,   setError]   = useState('')
  const [section, setSection] = useState('full document')
  const [exporting, setExporting] = useState({ docx: false, pdf: false })
  const [showExport, setShowExport] = useState(false)
  const [toast, setToast] = useState(null)
  const { hasRole } = useContext(AuthContext)
  const canEdit = hasRole('developer')
  const [editing, setEditing]         = useState(false)
  const [editMarkdown, setEditMarkdown] = useState('')
  const [planSaving, setPlanSaving]   = useState(false)

  useEffect(() => {
    if (plan?.jira_id) {
      document.title = `${plan.jira_id} — Test Plan | Testurai`
    } else {
      document.title = 'Test Plan | Testurai'
    }
  }, [plan?.jira_id])

  useEffect(() => {
    if (plan && plan.id === id) return; // Already have it from state
    axios.get(`/api/history/${id}`)
      .then(r => { setPlan(r.data.data); setLoading(false) })
      .catch(e => { setError(e.response?.data?.error || 'Not found'); setLoading(false) })
  }, [id, plan])

  function showToast(msg, type = 'info') {
    setToast({ msg, type })
    setTimeout(() => setToast(null), 3500)
  }

  async function handleShare() {
    const url = window.location.href
    try {
      await navigator.clipboard.writeText(url)
      showToast('Link copied to clipboard!', 'success')
    } catch {
      // Fallback for browsers that block clipboard API
      const el = document.createElement('textarea')
      el.value = url
      el.style.cssText = 'position:fixed;opacity:0;pointer-events:none'
      document.body.appendChild(el)
      el.select()
      const ok = document.execCommand('copy')
      document.body.removeChild(el)
      ok ? showToast('Link copied to clipboard!', 'success')
         : showToast(`Copy this link: ${url}`, 'info')
    }
  }

  async function handleExport(fmt) {
    setExporting(p => ({ ...p, [fmt]: true }))
    try {
      const r = await axios.get(`/api/export/${id}/${fmt}`, { responseType: 'blob' })
      const a = document.createElement('a')
      a.href = URL.createObjectURL(r.data)
      a.download = `${plan.jira_id}_test_plan.${fmt}`
      a.click()
      showToast(`${fmt.toUpperCase()} exported!`, 'success')
    } catch { showToast('Export failed — check server logs.', 'error') }
    finally { setExporting(p => ({ ...p, [fmt]: false })) }
  }

  async function handleSaveEdit() {
    setPlanSaving(true)
    try {
      const r = await axios.put(`/api/history/${id}`, { markdown: editMarkdown })
      setPlan(r.data.data)
      setEditing(false)
      showToast('Plan updated successfully!', 'success')
    } catch (e) {
      showToast(e.response?.data?.error || 'Save failed', 'error')
    } finally { setPlanSaving(false) }
  }

  if (loading) return (
    <div style={{ display:'flex', justifyContent:'center', alignItems:'center', minHeight:'60vh' }}>
      <div className="spinner" style={{ width:40, height:40 }} />
    </div>
  )

  if (error) return (
    <div className="empty-state">
      <div className="empty-icon">❌</div>
      <div className="empty-title">Not Found</div>
      <div className="empty-desc">{error}</div>
      <button className="btn btn-outline" style={{ marginTop:16 }} onClick={() => navigate('/history')}>← Back</button>
    </div>
  )

  const tcs = plan?.content?.test_cases || []
  const reviewed = tcs.filter(t => t.reviewed).length

  return (
    <div className="fade-in">
      {/* Header */}
      <div style={{ display:'flex', alignItems:'center', gap:12, marginBottom:6 }}>
        <button className="btn btn-ghost" style={{ padding:'6px 10px' }} onClick={() => navigate('/history')}>←</button>
        <span className="badge badge-cyan" style={{ fontSize:13, padding:'4px 12px' }}>{plan.jira_id}</span>
        <span style={{ fontWeight:700, fontSize:17 }}>{plan.jira_title}</span>
      </div>

      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:20 }}>
        <div style={{ fontSize:12, color:'var(--text-muted)' }}>
          Generated by <b style={{ color:'var(--text)' }}>{plan.llm_model}</b> on {formatDate(plan.generated_at)} • {tcs.length} Test Cases
        </div>
        <div style={{ display:'flex', gap:8 }}>
          {editing ? (
            <>
              <button className="btn btn-ghost" onClick={() => setEditing(false)}>✕ Cancel</button>
              <button className="btn btn-primary" onClick={handleSaveEdit} disabled={planSaving}>
                {planSaving ? <span className="spinner" style={{ width: 14, height: 14 }} /> : '💾'} Save Changes
              </button>
            </>
          ) : (
            <>
              {canEdit && (
                <button className="btn btn-outline" onClick={() => { setEditMarkdown(plan.content?.markdown || ''); setEditing(true) }}>✏ Edit</button>
              )}
              <button className="btn btn-outline" onClick={handleShare}>⇗ Share</button>
              <div style={{ position: 'relative' }}>
                <button className="btn btn-outline" onClick={() => setShowExport(!showExport)}>
                  📥 Export ▼
                </button>
                {showExport && (
                  <div style={{ position: 'absolute', top: '100%', right: 0, marginTop: 4, background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: 4, display: 'flex', flexDirection: 'column', gap: 4, zIndex: 10 }}>
                    <button className="btn btn-ghost" onClick={() => { setShowExport(false); handleExport('docx'); }} disabled={exporting.docx} style={{ justifyContent: 'flex-start', fontSize: 12 }}>
                      {exporting.docx ? <span className="spinner" style={{width:14,height:14}} /> : '📄'} DOCX
                    </button>
                    <button className="btn btn-ghost" onClick={() => { setShowExport(false); handleExport('pdf'); }} disabled={exporting.pdf} style={{ justifyContent: 'flex-start', fontSize: 12 }}>
                      {exporting.pdf ? <span className="spinner" style={{width:14,height:14}} /> : '📕'} PDF
                    </button>
                  </div>
                )}
              </div>
              <button className="btn btn-primary" onClick={() => navigate(`/generate?jira=${plan.jira_id}`)}>↺ Regenerate</button>
            </>
          )}
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'180px 1fr 220px', gap:20, alignItems:'start' }}>
        {/* Outline nav */}
        <div className="card" style={{ position:'sticky', top:20 }}>
          <div style={{ fontWeight:700, fontSize:13, marginBottom:12 }}>Navigation</div>
          {['Full Document', 'Test Cases', 'Statistics', 'Test Data'].map(s => (
            <div key={s} onClick={() => setSection(s.toLowerCase())}
              style={{
                padding:'7px 10px', borderRadius:'var(--radius-sm)', fontSize:13, cursor:'pointer',
                color: section===s.toLowerCase() ? 'var(--cyan)' : 'var(--text-muted)',
                background: section===s.toLowerCase() ? 'var(--cyan-dim)' : 'transparent',
                fontWeight: section===s.toLowerCase() ? 600 : 400, marginBottom:2, transition:'all 0.15s',
              }}>
              {s}
            </div>
          ))}
        </div>

        {/* Content */}
        <div>
          {editing ? (
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
                <div style={{ fontWeight: 600, fontSize: 14 }}>Edit Markdown</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                  {editMarkdown.split('\n').length} lines · {editMarkdown.length} characters
                </div>
              </div>
              <textarea
                value={editMarkdown}
                onChange={e => setEditMarkdown(e.target.value)}
                style={{
                  width: '100%', boxSizing: 'border-box', minHeight: '75vh',
                  background: 'var(--surface-2)', border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-sm)', color: 'var(--text)',
                  fontFamily: 'monospace', fontSize: 12, lineHeight: 1.7,
                  padding: '14px 16px', resize: 'vertical',
                }}
              />
            </div>
          ) : (
            <>
              {section === 'full document' && (
                <div className="card markdown-body" style={{ background:'var(--bg)', padding: '24px 32px' }}>
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {plan.content.markdown || ''}
                  </ReactMarkdown>
                </div>
              )}

              {section === 'test cases' && (
                <>
                  <div style={{ fontWeight:700, fontSize:16, marginBottom:16 }}>Test Case Details</div>
                  {tcs.length === 0 && (
                    <div className="empty-state"><div className="empty-icon">📋</div><div className="empty-title">No test cases parsed</div></div>
                  )}
                  {tcs.map(tc => (
                    <div key={tc.id} className="tc-card">
                      <div className="tc-header">
                        <span className="tc-id">{tc.id}</span>
                        <span className={`badge ${priorityBadge(tc.priority)}`}>{tc.priority}</span>
                        <span className={`badge ${tc.type?.toLowerCase()==='negative' ? 'badge-orange' : 'badge-blue'}`}>{tc.type}</span>
                      </div>
                      <div className="tc-title">{tc.title}</div>
                      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:16 }}>
                        <div>
                          {tc.preconditions?.length > 0 && <>
                            <div className="tc-section-label">Preconditions</div>
                            <ul className="tc-list">{tc.preconditions.map((p,i) => <li key={i}>{p}</li>)}</ul>
                          </>}
                          {tc.steps?.length > 0 && <>
                            <div className="tc-section-label" style={{ marginTop:12 }}>Steps</div>
                            <ul className="tc-list">{tc.steps.map((s,i) => <li key={i}>{i+1}. {s}</li>)}</ul>
                          </>}
                        </div>
                        <div>
                          {tc.expected_result && <>
                            <div className="tc-section-label">Expected Result</div>
                            <div style={{ fontSize:13, color:'var(--text)', marginBottom:10 }}>{tc.expected_result}</div>
                          </>}
                          {Object.keys(tc.test_data||{}).length > 0 && <>
                            <div className="tc-section-label">Test Data</div>
                            {Object.entries(tc.test_data).map(([k,v]) => (
                              <div key={k} style={{ fontSize:12, marginBottom:3 }}>
                                <b style={{ color:'var(--text)' }}>{k}:</b> <span style={{ fontFamily:'monospace', color:'var(--cyan)' }}>{v}</span>
                              </div>
                            ))}
                          </>}
                        </div>
                      </div>
                    </div>
                  ))}
                </>
              )}

              {section === 'statistics' && (
                <div className="card">
                  <div style={{ fontWeight:700, fontSize:16, marginBottom:16 }}>Statistics</div>
                  <table className="data-table">
                    <tbody>
                      {[['Jira Issue',plan.jira_id],['LLM Model',plan.llm_model],['Provider',plan.llm_provider],
                        ['Generated',formatDate(plan.generated_at)],['Gen Time',`${plan.generation_time_seconds}s`],
                        ['Test Cases',tcs.length],['Status',plan.status]
                      ].map(([k,v]) => (
                        <tr key={k}><td style={{ color:'var(--text-muted)', width:160 }}>{k}</td><td style={{ fontWeight:500 }}>{v}</td></tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {section === 'test data' && (
                <div>
                  <div style={{ fontWeight:700, fontSize:16, marginBottom:16 }}>Test Data</div>
                  {tcs.filter(tc => Object.keys(tc.test_data||{}).length > 0).map(tc => (
                    <div key={tc.id} className="card" style={{ marginBottom:12 }}>
                      <div style={{ display:'flex', gap:8, marginBottom:10 }}>
                        <span className="tc-id">{tc.id}</span>
                        <span style={{ fontWeight:600 }}>{tc.title}</span>
                      </div>
                      {Object.entries(tc.test_data).map(([k,v]) => (
                        <div key={k} style={{ display:'flex', gap:12, padding:'6px 12px', background:'var(--bg-card-2)', borderRadius:'var(--radius-sm)', marginBottom:4, fontSize:13 }}>
                          <span style={{ color:'var(--text-muted)', minWidth:100 }}>{k}</span>
                          <span style={{ fontFamily:'monospace', color:'var(--cyan)' }}>{v}</span>
                        </div>
                      ))}
                    </div>
                  ))}
                </div>
              )}
            </>
          )}
        </div>

        {/* Jump Links */}
        <div className="card" style={{ position:'sticky', top:20 }}>
          <div style={{ fontWeight:700, fontSize:13, marginBottom:14 }}>Jump Links</div>
          {[['Total',tcs.length,'var(--text)'],['Reviewed',reviewed,'var(--green)'],['Passed',0,'var(--green)'],['Untested',tcs.length-reviewed,'var(--text-muted)']].map(([l,v,c]) => (
            <div key={l} style={{ display:'flex', justifyContent:'space-between', padding:'7px 0', borderBottom:'1px solid var(--border)' }}>
              <span style={{ fontSize:13, color:'var(--text-muted)' }}>{l}</span>
              <span style={{ fontSize:13, fontWeight:700, color:c }}>{v}</span>
            </div>
          ))}
          <div style={{ marginTop:14, fontSize:12, color:'var(--text-muted)', marginBottom:4 }}>{reviewed} of {tcs.length} reviewed</div>
          <div className="progress-bar-wrap" style={{ marginBottom:16 }}>
            <div className="progress-bar-fill" style={{ width:`${tcs.length ? (reviewed/tcs.length)*100 : 0}%` }} />
          </div>
        </div>
      </div>

      {toast && <div className={`toast toast-${toast.type}`}>{toast.type==='success'?'✅':toast.type==='error'?'❌':'ℹ️'} {toast.msg}</div>}
    </div>
  )
}
